apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-management
spec:
  selector:
    matchLabels:
      app: user-management
  template:
    metadata:
      labels:
        app: user-management
    spec:
      containers:
      - env:
        - name: NODE_ENV
          value: "production"
        - name: NODE_PORT
          value: "8080"
        - name: APP_SECRET
          value: "thisissecret"
        name: user-management
        image: dzhurey/user-management:v1
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: user-management
spec:
  selector:
    app: user-management
  ports:
  - port: 80
    targetPort: 8080

